DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    full_name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS subjects;
CREATE TABLE subjects(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [name] VARCHAR(255) UNIQUE NOT NULL,
    teacher_id INTEGER,
    FOREIGN KEY (teacher_id) REFERENCES teachers (id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
);


DROP TABLE IF EXISTS [groups];
CREATE TABLE [groups](
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    [name] VARCHAR(8) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS students;
CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    group_id INTEGER,
    FOREIGN KEY (group_id) REFERENCES [groups] (id)
      ON DELETE SET NULL
      ON UPDATE CASCADE
);

DROP TABLE IF EXISTS students_subjects;
CREATE TABLE students_subjects (
  student_id INTEGER NOT NULL,
  subject_id INTEGER NOT NULL,
  primary key (student_id, subject_id),
  FOREIGN KEY (student_id) REFERENCES students (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
DROP TABLE IF EXISTS grades;
CREATE TABLE grades (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    student_id INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    grade INTEGER NOT NULL,
    date_of DATE NOT NULL,
    FOREIGN KEY (student_id) REFERENCES students (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
    FOREIGN KEY (subject_id) REFERENCES subjects (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE  
);